"""add safety_guides and training_records

Revision ID: 3f96fbb62b09
Revises: 33f10d304de9
Create Date: 2026-05-05 01:22:35.866525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f96fbb62b09'
down_revision: Union[str, Sequence[str], None] = '33f10d304de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_guides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('content_ko', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_guide_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guide_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('translated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['safety_guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guide_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['safety_guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_records')
    op.drop_table('safety_guide_translations')
    op.drop_table('safety_guides')
    # ### end Alembic commands ###
