"""add assignee due_date notifications

Revision ID: 8244e82a7505
Revises: 1ed708c416a6
Create Date: 2026-05-08 00:03:18.842773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8244e82a7505'
down_revision: Union[str, Sequence[str], None] = '1ed708c416a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incidents', sa.Column('assignee_id', sa.String(length=36), nullable=True))
    op.add_column('incidents', sa.Column('assignee_name', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('due_date', sa.DateTime(), nullable=True))
    # SQLite doesn't support ALTER FK, skip for now
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'due_date')
    op.drop_column('incidents', 'assignee_name')
    op.drop_column('incidents', 'assignee_id')
    op.drop_table('notifications')
    # ### end Alembic commands ###
